In [1]:
# Tensor, 可认为是一个高维数组

In [2]:
from __future__ import print_function
import torch as t

In [3]:
# 构建5×3矩阵，只是分配空间，未初始化
x = t.Tensor(5, 3)
x


 5.6171e+30  4.5642e-41  5.6171e+30
 4.5642e-41  2.7926e-14  4.5642e-41
 5.0377e+24  4.5642e-41  9.2292e+09
 4.5642e-41  2.8072e-14  4.5642e-41
 0.0000e+00  0.0000e+00  0.0000e+00
[torch.FloatTensor of size 5x3]

In [4]:
# 使用[0,1]均匀分布随机初始化二维数组
x = t.rand(5, 3)
x


 0.9150  0.1112  0.1797
 0.4541  0.2678  0.0429
 0.0931  0.7428  0.7344
 0.7634  0.2152  0.2491
 0.4979  0.9571  0.0331
[torch.FloatTensor of size 5x3]

In [5]:
print(x.size()) # 查看x的形状

torch.Size([5, 3])


In [9]:
x.size()[1] # 查看列的个数

3L

In [14]:
x.size()[0] # 查看行的个数

5L

In [15]:
x.size(1)

3

In [16]:
x.size(0)

5

In [17]:
# torch.size是tuple对象的子类，因此支持tuple的所有操作
y = t.rand(5, 3)

In [20]:
# 加法
x + y


 1.1669  0.9470  0.3525
 1.0727  0.2724  0.2495
 1.0031  1.6721  0.9746
 1.6818  1.0050  0.9906
 0.9317  1.2318  0.4863
[torch.FloatTensor of size 5x3]

In [22]:
# 加法2
t.add(x, y)


 1.1669  0.9470  0.3525
 1.0727  0.2724  0.2495
 1.0031  1.6721  0.9746
 1.6818  1.0050  0.9906
 0.9317  1.2318  0.4863
[torch.FloatTensor of size 5x3]

In [23]:
# 加法3
result = t.Tensor(5, 3) # 预先分配空间
t.add(x, y, out=result) # 输入到result
result


 1.1669  0.9470  0.3525
 1.0727  0.2724  0.2495
 1.0031  1.6721  0.9746
 1.6818  1.0050  0.9906
 0.9317  1.2318  0.4863
[torch.FloatTensor of size 5x3]

In [24]:
print('最初y')
print(y)

print('第一种加法，y的结果')
y.add(x) # 不改变y内容
print(y)

print('第二种加法，y的结果')
y.add_(x) # inplace加法，y变了
print(y)

最初y

 0.2519  0.8359  0.1729
 0.6187  0.0046  0.2066
 0.9100  0.9293  0.2403
 0.9183  0.7899  0.7415
 0.4338  0.2747  0.4533
[torch.FloatTensor of size 5x3]

第一种加法，y的结果

 0.2519  0.8359  0.1729
 0.6187  0.0046  0.2066
 0.9100  0.9293  0.2403
 0.9183  0.7899  0.7415
 0.4338  0.2747  0.4533
[torch.FloatTensor of size 5x3]

第二种加法，y的结果

 1.1669  0.9470  0.3525
 1.0727  0.2724  0.2495
 1.0031  1.6721  0.9746
 1.6818  1.0050  0.9906
 0.9317  1.2318  0.4863
[torch.FloatTensor of size 5x3]



In [26]:
# Tensor的选取操作与numpy类似
x


 0.9150  0.1112  0.1797
 0.4541  0.2678  0.0429
 0.0931  0.7428  0.7344
 0.7634  0.2152  0.2491
 0.4979  0.9571  0.0331
[torch.FloatTensor of size 5x3]

In [27]:
x[:, 1]


 0.1112
 0.2678
 0.7428
 0.2152
 0.9571
[torch.FloatTensor of size 5]

In [28]:
# Tensor不支持的操作，可以先转为numpy数组处理，之后再转回Tensor
a = t.ones(5) # 新建一个全是1的Tensor
a


 1
 1
 1
 1
 1
[torch.FloatTensor of size 5]

In [29]:
b = a.numpy() # Tensor -> Numpy
b

array([ 1.,  1.,  1.,  1.,  1.], dtype=float32)

In [34]:
import numpy as np
a = np.ones(5)
b = t.from_numpy(a) # Numpy->Tensor
print(a)
print(b)

[ 1.  1.  1.  1.  1.]

 1
 1
 1
 1
 1
[torch.DoubleTensor of size 5]



In [35]:
b.add_(1)
print(a)
print(b) # Tensor和Numpy共享内存

[ 2.  2.  2.  2.  2.]

 2
 2
 2
 2
 2
[torch.DoubleTensor of size 5]



In [36]:
# 支持CUDA的机器可以用下面这个
if t.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    x + y